### ISSUE TITLE
Neighbor List

### ISSUE THREAD

**Issue by wzy461143268** [mjhong0708/ase_extension#3]
I want to know how to use this function to build a graph from an  ase.Atoms object. I found a guidance from ase's documents. Could I follow  that guidance to use this extention? Dose this function can handle the PBC? I found that the graph used ase's method to be constructed is different from dig's radius_graph_pbc methods.

**Comment by mjhong0708** [comment]
Hello,

The usage of function `neighbor_list` is almost the same with `ASE`. The code is nothing but only API interface to `gchemol-neighbors` code, which is based on tree search algorithm. PBC is surely supported, but it cannot properly locate neighboring atom over more than two periodic boundaries, so be careful with cutoff radius.

**Comment by wzy461143268** [comment]
> Hello,
> 
> The usage of function `neighbor_list` is almost the same with `ASE`. The code is nothing but only API interface to `gchemol-neighbors` code, which is based on tree search algorithm. PBC is surely supported, but it cannot properly locate neighboring atom over more than two periodic boundaries, so be careful with cutoff radius.

thanks a lot!
